### ISSUE TITLE
Request for updated source code

### ISSUE THREAD

**Issue by ajp-ic-sg** [GluuFederation/ios-super-gluu#11]
Hello, I noticed that there is an update available on the Appstore for this repository with version ~~40.4.2~~ 40.4.4. However, the source code in this repository is still using version 34.1.0.

Could you please push the updated code to avoid any errors for me? Thank you.

**Comment by nynymike** [comment]
Checking

**Comment by ajp-ic-sg** [comment]
@nynymike Any update?

**Comment by nynymike** [comment]
Code was updated on Feb 3, 2022. You can "Watch" the project in Github, and you should receive notifications.

**Comment by christian-hawk** [comment]
@ajp-ic-sg I realized that there is a fresh [**super-gluu** repository](https://github.com/GluuFederation/super-gluu) containing `ios` and `android` folders. Looks like both project os (android + iOS)  resides in the same repository now.

**Comment by ajp-ic-sg** [comment]
@christian-hawk Ohh I see, thought they were still using this repository. Thank you anyway!
