### ISSUE TITLE
Enrollment through CASA not working 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/ios-super-gluu#12]
- iOS version: 4.4.2 ( released around 1w+/- ago ). 
- Enrollment failing for new user who are trying to use this newly released SuperGluu app in their iOS. 
- How to reproduce: 
   - Log into CASA portal
   - Try to enroll / add SuperGluu Device [ scan QR code ] 
   - Error appear in SuperGluu app. 
   
   
![Screenshot from 2023-01-04 22-14-53](https://user-images.githubusercontent.com/7156097/210609031-f2e46486-51f3-4b41-893b-e10da693255c.png)

![IMG_1716](https://user-images.githubusercontent.com/7156097/210609154-94876952-0866-40d6-907b-cd047117a05b.jpg)

**Comment by NazarYavornytskyy** [comment]
Fixed
