### ISSUE TITLE
iOS: better handling for Super Gluu enrollment/authentication with bad cert servers

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/ios-super-gluu#2]
Actual: The app (v34.0.4, 3) crashes when you try to enroll the device/authenticate against a server without proper certificates. 

Expected: The app doesn't crash. There is a pop-up saying:

 **Certificate error** (header)
Add a signed certificate, or turn on Trust All (SSL). (description)

**Comment by NazarYavornytskyy** [comment]
Fixed on oxPush side by adding better error handling
