### ISSUE TITLE
iOS: Add Trust All (SSL) toggle

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/ios-super-gluu#3]
Please add a toggle to enable/disable Trust All (SSL), just like it's done for Android:

![ssl](https://user-images.githubusercontent.com/38302725/48198035-aad81200-e3ab-11e8-9e3f-cc813cbf6ae1.png)
![certs](https://user-images.githubusercontent.com/38302725/48198243-5719f880-e3ac-11e8-8f88-7ce3a1bf7686.png)
![admin](https://user-images.githubusercontent.com/38302725/48198254-613bf700-e3ac-11e8-9019-650f0cc81673.png)

**Comment by NazarYavornytskyy** [comment]
Waiting for review

**Comment by NazarYavornytskyy** [comment]
Added Trust All toggle due commit 8cd07ae4090beaa525f6d3dee5fce5b45b26257a
